<<: !include "../hpack/module.yaml"
name:                servant-util
version:             0.1.0
copyright:           "2019 Serokell OÜ"
synopsis:            Servant servers utilities.
category:            Web

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- data-default
- fmt
- http-types
- megaparsec
- mtl
- pretty-terminal
- safe-exceptions
- servant
- servant-client
- servant-client-core
- servant-generic
- servant-server
- text
- text-format
- time
- reflection
- universum
- wai

library:
  source-dirs: src

  build-tools:
    - autoexporter

<<: *ghc-options

executables:
  servant-util-examples:
    <<: *exec-common
    source-dirs:         examples

    dependencies:
      - aeson
      - servant-util
      - warp
      - wai-extra

tests:
  servant-util-test:
    <<: *test-common
    dependencies:
      - hspec
      - servant-util
      - QuickCheck

<<: *default-extensions
