<<: !include "../hpack/module.yaml"
name:                servant-util
version:             0.1.0
copyright:           "2019 Serokell OÜ"
synopsis:            Servant servers utilities.
category:            Web

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- data-default
- fmt
- http-types
- megaparsec
- mtl
- pretty-terminal
- safe-exceptions
- servant
- servant-client
- servant-client-core
- servant-generic
- servant-server
- text
- text-format
- time
- reflection
- universum

library:
  source-dirs: src

  build-tools:
    - autoexporter

<<: *ghc-options

executables:
  servant-util-examples:
    <<: *exec-common
    source-dirs:         examples

tests:
  servant-util-test:
    <<: *test-common

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns
