# When you update the resolver or add new packages to `extra-deps`, you should
# also bump hackage and stackage indexes used by CI:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-14.16

packages:
- servant-util
- servant-util-beam-pg

extra-deps:
- pretty-terminal-0.1.0.0

nix:
  packages: [zlib, postgresql]
