# When you update the resolver or add new packages to `extra-deps`, you should
# also bump hackage and stackage indexes used by CI:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-19.31

packages:
  - servant-util
  - servant-util-beam-pg

extra-deps:
  - pretty-terminal-0.1.0.0
  - beam-core-0.9.2.1
  - beam-postgres-0.5.2.1
  - beam-migrate-0.5.1.2
  - dependent-map-0.4.0.0
  - dependent-sum-0.7.1.0
  - constraints-extras-0.3.2.1
  - network-uri-json-0.4.0.0
  - hspec-2.8.5
  - servant-openapi3-2.0.1.3
  - git: https://github.com/eir-forsakring/text-format
    commit: 3d151955c3cce0812ba1ade6cd65ded8d9142757

nix:
  packages: [lzma, zlib, postgresql]
