# When you update the resolver or add new packages to `extra-deps`, you should
# also bump hackage and stackage indexes used by CI:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-18.21

packages:
- servant-util
- servant-util-beam-pg

extra-deps:
- pretty-terminal-0.1.0.0
- beam-core-0.9.0.0
- beam-postgres-0.5.0.0
- beam-migrate-0.5.0.0
- dependent-map-0.4.0.0
- dependent-sum-0.7.1.0
- constraints-extras-0.3.0.2
- network-uri-json-0.4.0.0
- hspec-2.7.9

allow-newer: true

nix:
  packages: [lzma, zlib, postgresql]
